name: Claude Touch

on:
  schedule:
    - cron: '15 20 * * *' #jst5:15
  workflow_dispatch: #テスト用マニュアル実行

jobs:
  claude-touch:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run Claude Code
        uses: grll/claude-code-action@beta
        with:
          use_oauth: 'true'
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          timeout_minutes: '5'
          model: 'claude-sonnet-4-20250514'
          allowed_tools: 'Bash(echo*)'
          direct_prompt: |
            This is a confirmation of operation.
            Output "hello" with the bash echo command.
            Once done, exit immediately.
