name: Daily Issue (Weekdays 05:15 JST)

on:
  schedule:
    # JST 05:15 == 前日 20:15 (UTC)
    # → 月〜金(JST) = 日〜木(UTC)
    - cron: '15 20 * * SUN-THU'
  workflow_dispatch: # 手動実行

permissions:
  # 既定は read-all なので明示的に書き換える
  issues: write   # Issue 作成に必要
  contents: read  # repo 情報を読むだけなら read で十分

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Post Issue with github-script
        uses: actions/github-script@v7
        with:
          script: |
            // JST で日付を成形
            const dateJst = new Date(
              new Date().toLocaleString('en-US', { timeZone: 'Asia/Tokyo' })
            ).toISOString().slice(0, 10);  // YYYY-MM-DD

            const title = `claude-touch ${dateJst}`;
            const body = ` @claude これは実験用のテストスクリプトです。コメントに"touch"と記入したら何もせずに直ちに処理を終了してください `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              title,
              body,
            });